Header header

# Whether active compliance should be enabled (IGNORED)
bool active_compliance
# The desired fingers for the grasp
# True: move finger to position and apply given effort
# False: leave finger at current position and don't apply effort
bool[3] grasp_mask
# The desired grasp speed (rad/s in the medial joint)
float64[3] grasp_speed
# If the inner links close past this position, the grasp will be treated as a failure
flaot64[3] grasp_position
# The effort that should be applied once the fingers stop
float64[3] grasp_effort
---
---
